### ISSUE TITLE
java.lang.AbstractMethodError

### ISSUE THREAD

**Issue by fly-qp** [Vungle/Flutter-Plugin#12]
I don't know why and how but crashlytics (firebase) informed me about this issue. Happened for more than 22.000 user.  Please fix this issue.

Stack trace:
Fatal Exception: java.lang.AbstractMethodError: abstract method "void com.vungle.warren.PlayAdCallback.creativeId(java.lang.String)"
       at com.vungle.warren.PlayAdCallbackWrapper$1.run(PlayAdCallbackWrapper.java:24)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8653)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by stanley-vungle** [comment]
update to a newer version of android sdk
