### ISSUE TITLE
No Event id passed for HBP

### ISSUE THREAD

**Issue by hautvfami** [Vungle/Flutter-Plugin#20]
E/VunglePlugin(23476): Vungle ad load failed, *****INTERSTITIAL-025****, 
E/VunglePlugin(23476): com.vungle.warren.error.VungleException: No Event id passed for HBP
E/VunglePlugin(23476): 	at com.vungle.warren.AdLoader.loadAd(AdLoader.java:643)
E/VunglePlugin(23476): 	at com.vungle.warren.AdLoader.startLoading(AdLoader.java:504)
E/VunglePlugin(23476): 	at com.vungle.warren.AdLoader.access$600(AdLoader.java:103)
E/VunglePlugin(23476): 	at com.vungle.warren.AdLoader$2.run(AdLoader.java:458)
E/VunglePlugin(23476): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/VunglePlugin(23476): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/VunglePlugin(23476): 	at java.lang.Thread.run(Thread.java:923)

**Comment by chipmunkk-studio** [comment]
is that fixed?

**Comment by courtneypresto** [comment]
@hautvfami @chipmunkk-studio  -- yeah I'm having the same issue

**Comment by keetamhoang** [comment]
Haiz, bad package
