### ISSUE TITLE
Android Rewarded Ads Display Issue

### ISSUE THREAD

**Issue by chipmunkk-studio** [Vungle/Flutter-Plugin#22]
```
E/com.vungle.warren.AdLoader(11661): Failed to load Ad/Assets for AdRequest
E/com.vungle.warren.AdLoader(11661): com.vungle.warren.error.VungleException: No Event id passed for HBP
E/com.vungle.warren.AdLoader(11661): 	at com.vungle.warren.AdLoader.loadAd(AdLoader.java:643)
E/com.vungle.warren.AdLoader(11661): 	at com.vungle.warren.AdLoader.startLoading(AdLoader.java:504)
E/com.vungle.warren.AdLoader(11661): 	at com.vungle.warren.AdLoader.access$600(AdLoader.java:103)
E/com.vungle.warren.AdLoader(11661): 	at com.vungle.warren.AdLoader$2.run(AdLoader.java:458)
```

We are currently experiencing an issue with the non-display of rewarded ads on Android devices, while there are no such problems on iOS. We sincerely hope for a prompt check and resolution of this matter. Your assistance in this regard would be greatly appreciated.

**Comment by courtneypresto** [comment]
I'm having the same issue -- did you fix it somehow? @chipmunkk-studio
